'use client'

import { useMemo, useState } from 'react'
import type { PassportSource } from '@/lib/passport-sources'

type Photo = { id: string; url: string; phase: string; category?: string | null; caption?: string | null; createdAt?: string }
type Timeline = { id: string; summary: string; createdAt: string; status?: string | null }
type Document = { id: string; title: string; document_type: string; year?: number | null; version: number }

const staffNav = ['overview','timeline','photos','storm-history','maintenance','documents','policy-vault','certificates','sources','next-actions']
const publicNav = ['overview','photos','timeline','storm-history','maintenance','documents','sources','next-actions']
const label = (value: string) => value.replaceAll('-', ' ').replaceAll('_', ' ')

export default function PassportExperience({ property, photos, timeline, documents, sources, publicMode = false, measurement }: {
  property: { address: string; neighborhood?: string | null; fieldScore?: number | null; observations?: string[]; roofAge?: number | null; status: string; reportVersion: number; inspectionDate?: string | null; representative?: string | null; roofCovering?: string | null; footprintSqft?: number | null; pitchMultiplier?: number | null; wasteFactor?: number | null }
  photos: Photo[]; timeline: Timeline[]; documents: Document[]; sources: PassportSource[]; publicMode?: boolean
  measurement?: { source: string; retrievedAt: string; coverageStatus: string; confidence: string; roofSquares: number | null; limitations: string } | null
}) {
  const [area, setArea] = useState(property.footprintSqft || 0)
  const [pitch, setPitch] = useState(property.pitchMultiplier || 1.12)
  const [waste, setWaste] = useState(property.wasteFactor || 0.1)
  const [annualMaintenance, setAnnualMaintenance] = useState(0)
  const [reactiveVisits, setReactiveVisits] = useState(0)
  const [reactiveVisitCost, setReactiveVisitCost] = useState(0)
  const [deductible, setDeductible] = useState(0)
  const squares = area > 0 ? (area * pitch * (1 + waste)) / 100 : null
  const economics = useMemo(() => ({ planned: annualMaintenance, reactive: reactiveVisits * reactiveVisitCost, deductible }), [annualMaintenance, reactiveVisits, reactiveVisitCost, deductible])
  const preliminary = photos.filter((photo) => photo.phase === 'pre_knock')
  const full = photos.filter((photo) => photo.phase === 'full_house')
  const policyDocs = documents.filter((doc) => doc.document_type === 'insurance_policy')
  const certificates = documents.filter((doc) => doc.document_type.includes('certificate'))

  return <div className="min-h-screen bg-[#080b13] text-white">
    <header className="border-b border-[#d4af37]/30 bg-black px-6 py-6"><div className="mx-auto flex max-w-6xl items-center justify-between"><div><div className="text-xs font-bold tracking-[4px] text-[#d4af37]">ASC EDGE</div><div className="mt-1 text-sm text-white/55">ROOF PASSPORT • ROOFING ASSET MANAGER</div></div><div className="rounded-full border border-white/15 px-4 py-2 text-xs uppercase tracking-wider text-white/65">{label(property.status)}</div></div></header>
    <nav className="sticky top-0 z-40 overflow-x-auto border-b border-white/10 bg-[#080b13]/95 px-4 backdrop-blur"><div className="mx-auto flex w-max max-w-6xl gap-1 py-3">{(publicMode ? publicNav : staffNav).map((item) => <a key={item} href={`#${item}`} className="rounded-full px-3 py-2 text-xs capitalize text-white/60 hover:bg-white/10 hover:text-white">{label(item)}</a>)}</div></nav>
    <main className="mx-auto max-w-6xl space-y-20 px-6 py-12">
      <section id="overview" className="scroll-mt-24"><div className="text-xs font-bold tracking-[3px] text-[#d4af37]">EXECUTIVE PROPERTY SUMMARY</div><h1 className="mt-4 text-4xl font-bold md:text-6xl">{property.address}</h1>{property.neighborhood && <p className="mt-2 text-xl text-white/50">{property.neighborhood}</p>}<div className="mt-8 grid gap-4 md:grid-cols-4">{[['Report version', `v${property.reportVersion}`],['Inspection date', property.inspectionDate || 'Pending verification'],['Responsible user', property.representative || 'Assigned representative'],['Images', `${photos.length} chronological`]].map(([k,v]) => <div key={k} className="rounded-3xl border border-white/10 bg-[#111827] p-5"><div className="text-xs uppercase tracking-wider text-white/40">{k}</div><div className="mt-2 font-semibold">{v}</div></div>)}</div>
        <div className="mt-8 grid gap-6 lg:grid-cols-2"><div className="rounded-3xl border border-[#d4af37]/25 bg-[#d4af37]/5 p-7"><h2 className="text-2xl font-semibold">A continuing record—not a one-time report</h2><p className="mt-4 leading-relaxed text-white/70">A replacement is a transaction. A Roof Passport keeps identification, photographs, authorizations, maintenance, documents, and annual updates connected to the same home asset over time.</p><p className="mt-4 text-sm text-white/50">“Roofing Asset Manager” is a working relationship title subject to brand and legal review.</p></div><div className="rounded-3xl border border-white/10 bg-[#111827] p-7"><h2 className="text-xl font-semibold">Property and roof characteristics</h2><dl className="mt-4 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-white/40">Roof covering</dt><dd className="mt-1">{property.roofCovering || 'Pending documentation'}</dd></div><div><dt className="text-white/40">Roof age</dt><dd className="mt-1">{property.roofAge ?? 'Unknown'}</dd></div><div><dt className="text-white/40">Condition indicator</dt><dd className="mt-1">{property.fieldScore ?? 'Not scored'} / 10</dd></div><div><dt className="text-white/40">Evidence classification</dt><dd className="mt-1">Representative observations</dd></div></dl></div></div>
        {publicMode ? <div className="mt-8 rounded-3xl border border-[#d4af37]/25 bg-[#d4af37]/5 p-7"><h2 className="text-xl font-semibold">Preliminary roof measurement</h2>{measurement?.roofSquares ? <><div className="mt-5 text-3xl font-bold text-[#d4af37]">Estimated roof area: {measurement.roofSquares.toFixed(1)} squares</div><dl className="mt-5 grid gap-3 text-sm md:grid-cols-3"><div><dt className="text-white/40">Source</dt><dd className="mt-1">{measurement.source === 'google_solar' ? 'Google Solar building and roof analysis' : label(measurement.source)}</dd></div><div><dt className="text-white/40">Retrieved</dt><dd className="mt-1">{new Date(measurement.retrievedAt).toLocaleDateString()}</dd></div><div><dt className="text-white/40">Coverage / confidence</dt><dd className="mt-1">{label(measurement.coverageStatus)} / {label(measurement.confidence)}</dd></div></dl><p className="mt-4 text-sm text-white/60">{measurement.limitations}</p></> : <p className="mt-3 text-white/60">Primary provider coverage is being verified. If unavailable, an authorized staff member will document approved fallback evidence and manual review.</p>}</div> : <div className="mt-8 rounded-3xl border border-white/10 p-7"><h2 className="text-xl font-semibold">Quick roof square-count estimate</h2><p className="mt-2 text-sm text-white/55">Internal educational estimate only; this is not an order quantity.</p><div className="mt-5 grid gap-3 md:grid-cols-3"><label className="text-xs text-white/50">Footprint sq ft<input type="number" value={area || ''} onChange={(e)=>setArea(Number(e.target.value))} className="mt-2 w-full rounded-xl bg-white/10 p-3 text-white" /></label><label className="text-xs text-white/50">Pitch multiplier<input type="number" step="0.01" value={pitch} onChange={(e)=>setPitch(Number(e.target.value))} className="mt-2 w-full rounded-xl bg-white/10 p-3 text-white" /></label><label className="text-xs text-white/50">Waste factor<input type="number" step="0.01" value={waste} onChange={(e)=>setWaste(Number(e.target.value))} className="mt-2 w-full rounded-xl bg-white/10 p-3 text-white" /></label></div><div className="mt-5 text-3xl font-bold text-[#d4af37]">{squares ? `${squares.toFixed(1)} squares estimated` : 'Enter footprint to estimate'}</div></div>}
      </section>

      <section id="timeline" className="scroll-mt-24"><SectionTitle title="Property timeline" subtitle="Chronological, append-only history" /><div className="space-y-3">{timeline.length ? timeline.map((event)=><div key={event.id} className="rounded-2xl border border-white/10 p-5"><div className="text-xs text-white/40">{new Date(event.createdAt).toLocaleString()} {event.status ? `• ${label(event.status)}` : ''}</div><p className="mt-2 text-white/75">{event.summary}</p></div>) : <Empty text="Timeline events will appear as documentation is added." />}</div></section>

      <section id="photos" className="scroll-mt-24"><SectionTitle title="Ordered photographic record" subtitle={`${preliminary.length} preliminary • ${full.length} full documentation`} /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{photos.map((photo)=><figure key={photo.id} className="overflow-hidden rounded-3xl border border-white/10 bg-[#111827]"><img src={photo.url} alt={photo.caption || 'Property documentation'} className="aspect-video w-full object-cover" /><figcaption className="p-4"><div className="text-xs uppercase tracking-wider text-[#d4af37]">{label(photo.category || photo.phase)}</div><p className="mt-2 text-sm text-white/60">{photo.caption || 'Visual observation; definitive diagnosis not established.'}</p></figcaption></figure>)}</div></section>

      <section id="storm-history" className="scroll-mt-24"><SectionTitle title="Storm history" subtitle="Property relevance must be established—regional reports alone do not prove damage at this address" /><div className="grid gap-4 md:grid-cols-2"><Card title="NOAA/NCEI record"><p>Use quality-controlled Storm Data and the Storm Events Database. Recent events may not yet be finalized.</p><Tag>THIRD-PARTY DATA</Tag></Card><Card title="Hail and wind evidence"><p>No property-specific hail swath or wind measurement is asserted until a verified dataset is attached to this Passport.</p><Tag>NOT YET VERIFIED</Tag></Card><Card title="Institutional hail imagery"><p>No university hail imagery is displayed because its institution, license, date, and property relevance have not been verified.</p><Tag>INTENTIONALLY UNAVAILABLE</Tag></Card><Card title="Building-code update protocol"><p>Record the permit jurisdiction, applicable code edition, adoption date, amendments, permit, and inspection evidence for each project version. Confirm requirements with the authority having jurisdiction.</p><Tag>PROTOCOL</Tag></Card></div></section>

      <section id="maintenance" className="scroll-mt-24"><SectionTitle title="Maintenance" subtitle="Picture-to-Price workflow and homeowner-controlled educational assumptions" />{property.observations?.length ? <div className="grid gap-3 md:grid-cols-2">{property.observations.map((item)=><Card key={item} title="Representative observation"><p>{item}</p><button className="mt-4 rounded-xl border border-[#d4af37]/40 px-4 py-2 text-xs text-[#d4af37]">REQUEST PICTURE-TO-PRICE REVIEW</button></Card>)}</div> : <Empty text="No maintenance observations have been recorded." />}
        <div className="mt-8 rounded-3xl border border-white/10 bg-[#111827] p-7"><h3 className="text-xl font-semibold">Maintenance economics explorer</h3><p className="mt-2 text-sm text-white/50">Your assumptions only. This does not predict claims, coverage, premium savings, or replacement timing.</p><div className="mt-5 grid gap-3 md:grid-cols-4">{[['Annual planned maintenance',annualMaintenance,setAnnualMaintenance],['Reactive visits per year',reactiveVisits,setReactiveVisits],['Cost per reactive visit',reactiveVisitCost,setReactiveVisitCost],['Deductible exposure',deductible,setDeductible]].map(([title,value,setter])=><label key={title as string} className="text-xs text-white/50">{title as string}<input type="number" value={value as number || ''} onChange={(e)=>(setter as (n:number)=>void)(Number(e.target.value))} className="mt-2 w-full rounded-xl bg-white/10 p-3 text-white" /></label>)}</div><div className="mt-6 grid gap-3 md:grid-cols-3"><Metric title="Planned annual" value={economics.planned}/><Metric title="Reactive visits" value={economics.reactive}/><Metric title="Entered deductible" value={economics.deductible}/></div></div>
        <div className="mt-6 rounded-3xl border border-[#d4af37]/25 bg-[#d4af37]/5 p-7"><h3 className="text-xl font-semibold">Annual maintenance plan</h3><p className="mt-3 text-white/65">Review visible roof covering, flashing, penetrations, gutters, drainage, nearby limbs, interior leak indicators, and changes since the prior record. Use a qualified professional where safe access or technical assessment is needed.</p></div>
      </section>

      <section id="documents" className="scroll-mt-24"><SectionTitle title="Documents and authorizations" subtitle="Versioned records; corrections append rather than overwrite" />{documents.length ? documents.map((doc)=><div key={doc.id} className="mb-3 rounded-2xl border border-white/10 p-4"><b>{doc.title}</b><span className="ml-3 text-xs text-white/40">{label(doc.document_type)} • v{doc.version}{doc.year ? ` • ${doc.year}` : ''}</span></div>) : <Empty text="No property documents are stored yet." />}</section>

      {!publicMode && <section id="policy-vault" className="scroll-mt-24"><SectionTitle title="Insurance policy vault" subtitle="Secure year-over-year versions with neutral AI-assisted extraction" />{policyDocs.length ? policyDocs.map((doc)=><Card key={doc.id} title={`${doc.title} • ${doc.year || 'Year not set'} • v${doc.version}`}><p>Available to authorized users. Any extracted change or discrepancy requires professional review.</p></Card>) : <Empty text="No policy documents are stored. Upload controls will require separate policy-vault authorization." />}<div className="mt-6 rounded-3xl border border-red-300/20 bg-red-300/5 p-7"><h3 className="font-semibold">Professional-review boundary</h3><p className="mt-3 text-sm leading-relaxed text-white/65">AI may extract facts, compare years, and flag changed language, limits, or endorsements. It does not determine coverage, interpret legal rights, negotiate claims, or act as an insurance agent, attorney, or public adjuster. Ask the appropriate licensed insurance agent, public adjuster, or attorney when interpretation is required.</p></div></section>}

      {!publicMode && <section id="certificates" className="scroll-mt-24"><SectionTitle title="Certificates" subtitle="Texas Windstorm/TWIA certificate lookup and stored evidence" /><a href="https://www.tdi.texas.gov/wind/index.html" target="_blank" rel="noreferrer" className="inline-block rounded-2xl bg-[#d4af37] px-5 py-3 font-bold text-[#080b13]">OPEN OFFICIAL TDI WINDSTORM LOOKUP</a><div className="mt-5">{certificates.length ? certificates.map((doc)=><Card key={doc.id} title={doc.title}><p>Stored certificate version {doc.version}.</p></Card>) : <Empty text="No certificate is asserted or stored for this property yet." />}</div></section>}

      <section id="sources" className="scroll-mt-24"><SectionTitle title="Source and citation registry" subtitle="Every educational claim is tied to a publisher and report section" /><div className="space-y-4">{sources.map((source)=><article key={source.id} className="rounded-3xl border border-white/10 p-6"><div className="text-xs font-bold uppercase tracking-wider text-[#d4af37]">{source.publisher}</div><a href={source.url} target="_blank" rel="noreferrer" className="mt-2 block text-lg font-semibold underline decoration-white/25">{source.title}</a><p className="mt-3 text-sm text-white/65">{source.claim}</p><div className="mt-4 text-xs text-white/35">Published/revised: {source.published} • Accessed: {source.accessed} • Sections: {source.sections.join(', ')}</div></article>)}</div></section>

      <section id="next-actions" className="scroll-mt-24"><SectionTitle title="Next actions" subtitle="A red-carpet home office for the roof and its continuing record" /><div className="grid gap-4 md:grid-cols-2"><Card title="1. Complete the record"><p>Confirm property characteristics, categorize photographs, resolve open maintenance items, and attach genuinely applicable documents.</p></Card><Card title="2. Review with the right professional"><p>Route roofing, engineering, insurance, public-adjusting, or legal questions to appropriately qualified or licensed professionals.</p></Card><Card title="3. Plan the annual update"><p>Compare current conditions and documents with the prior year instead of starting over with disconnected inspections.</p></Card><Card title="4. Establish the relationship"><p>The Roofing Asset Manager helps keep the roof identified, documented, monitored, maintained, and updated over time.</p></Card></div>
        <div className="mt-8 rounded-3xl border border-[#d4af37]/30 bg-[#d4af37]/5 p-8"><div className="text-xs font-bold tracking-widest text-[#d4af37]">WINDOW STICKER CONCEPT</div><h3 className="mt-3 text-2xl font-semibold">An established roofing relationship</h3><p className="mt-3 max-w-3xl text-white/65">The sticker can indicate that this property has a continuing Roof Passport and service relationship. Its QR must open only a purpose-limited secure experience—never private documents, policy files, or a guessable property identifier.</p></div>
        <div className="mt-6 grid gap-4 md:grid-cols-2">{['Autonomous Drone Flight Reports — Coming Soon','AI Glasses Inspection Reports — Coming Soon'].map((item)=><Card key={item} title={item}><p>Future capability under development; not currently available or included in this Passport.</p></Card>)}</div>
      </section>
    </main>
    <footer className="border-t border-white/10 px-6 py-10 text-center text-xs text-white/35">Educational documentation only. No insurance coverage, legal rights, claim outcome, premium reduction, or maintenance result is promised.</footer>
  </div>
}

function SectionTitle({ title, subtitle }: { title: string; subtitle: string }) { return <div className="mb-7"><div className="text-xs font-bold tracking-[3px] text-[#d4af37]">{title.toUpperCase()}</div><p className="mt-2 text-white/50">{subtitle}</p></div> }
function Card({ title, children }: { title: string; children: React.ReactNode }) { return <div className="rounded-3xl border border-white/10 bg-[#111827] p-6"><h3 className="text-lg font-semibold">{title}</h3><div className="mt-3 text-sm leading-relaxed text-white/65">{children}</div></div> }
function Empty({ text }: { text: string }) { return <div className="rounded-3xl border border-dashed border-white/15 p-7 text-sm text-white/45">{text}</div> }
function Tag({ children }: { children: React.ReactNode }) { return <div className="mt-4 inline-block rounded-full bg-white/10 px-3 py-1 text-[10px] font-bold tracking-wider text-white/55">{children}</div> }
function Metric({ title, value }: { title: string; value: number }) { return <div className="rounded-2xl bg-black/25 p-4"><div className="text-xs text-white/40">{title}</div><div className="mt-1 text-xl font-bold">${value.toLocaleString()}</div></div> }
